import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from './components/header'
import Footer from './components/footer'




export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next-Js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        
        <h1 className={styles.title}>
          Learning Next.js!
        </h1>

        <div>
          <ul >
            <li><Link href='/link'><a className={styles.a}>Esto es un Link totalmente centrado</a></Link></li>
            <li><Link href='/link2'><a className={styles.a}>Esto es otro link que esta vacio</a></Link></li>
            <li><Link href='/grid'><a className={styles.a}>Grid</a></Link></li>
            <li><Link href='/test'><a className={styles.a}> y Aqui es solo un Test</a></Link></li>
          </ul>
        </div>

        <div>
          <ul >
            <li><Link href='/link'><a className={styles.a}>Esto es un Link totalmente centrado</a></Link></li>
            <li><Link href='/link2'><a className={styles.a}>Esto es otro link que esta vacio</a></Link></li>
            <li><Link href='/link3'><a className={styles.a}>Esto es otro link que esta vacio</a></Link></li>
            <li><Link href='/test'><a className={styles.a}> y Aqui es solo un Test</a></Link></li>
          </ul>
        </div>

        <div>
          <ul >
            <li><Link href='/link'><a className={styles.a}>Esto es un Link totalmente centrado</a></Link></li>
            <li><Link href='/link2'><a className={styles.a}>Esto es otro link que esta vacio</a></Link></li>
            <li><Link href='/link3'><a className={styles.a}>Esto es otro link que esta vacio</a></Link></li>
            <li><Link href='/test'><a className={styles.a}> y Aqui es solo un Test</a></Link></li>
          </ul>
        </div>
        
      </main>

      <Footer />
        
    </div>
  )
}
